name: Format
on:
  push:
    branches: [main]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command
    - uses: cachix/cachix-action@v8
      with:
        name: quickstrom
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Format Haskell code
      run: nix-shell -p '(import ./nix/nixpkgs.nix {}).ormolu' --run tools/format-code.sh
    - name: Format Rust code
      run: cd rust; nix-shell -p '(import ../nix/nixpkgs.nix {}).rustfmt' --run tools/format-code.sh
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4.1.2
      with:
        commit_message: Auto-format source code
        branch: ${{ github.head_ref }}