name: "Build and test"
on:
  pull_request:
  push:
jobs:

  build:
    strategy: 
      matrix: 
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v8
      with:
        name: quickstrom
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix show-config
    - run: nix-build default.nix
    - run: nix-shell --run "echo OK"