name: "Build and test"
on:
  pull_request:
  push:
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v14
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command
    - uses: cachix/cachix-action@v10
      with:
        name: quickstrom
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix show-config
    - run: nix-build default.nix
    - run: nix-shell --run "echo OK"